# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
exclude: '^docs/'
fail_fast: true
repos:
- repo: https://github.com/pylint-dev/pylint
  rev: v3.0.2
  hooks:
    - id: pylint
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      name: isort (python)
      args: [--sl]
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.7.1
  hooks:
    - id: mypy
- repo: local
  hooks:
    - id: pytest
      types: [python]
      name: pytest
      entry: python -m pytest -vv
      language: system
      pass_filenames: false
